### ISSUE TITLE
Access Denied on S3 template URL as of 2022-05-12

### ISSUE THREAD

**Issue by tinuzz** [aws-samples/1click-hpc#12]
As of today, the template URL https://enginframe.s3.amazonaws.com/AWS-HPC-Cluster.yaml returns an Access Denied error.

Yesterday, I was able to deploy the 1click-hpc solution without problems.

**Comment by nicolaven** [comment]
Thanks! it should be fixed now. 
Can you please try again?

**Comment by tinuzz** [comment]
Yes, it works! Thank you,

**Comment by piraka9011** [comment]
@nicolaven this is now occurring again. Did some thing change recently?
