### ISSUE TITLE
Can't use my own Active Directory

### ISSUE THREAD

**Issue by rvencu** [aws-samples/1click-hpc#16]
Getting this after leaving everything on AUTO but Active Directory

Template format error: Unresolved resource dependencies [ActiveDirectory] in the Resources block of the template

**Comment by rvencu** [comment]
Hm, 

Directory under maintenance
This directory is currently undergoing maintenance (for example, taking snapshots or applying patches). This can take from a few minutes up to an hour. During this process some functionalities will be unavailable.

This is a fresh new directory.

**Comment by rvencu** [comment]
After maintenance - got the same error. I added then the VPC and the public subnets exactly as the AD has them. Same problem

**Comment by nicolaven** [comment]
Hi @rvencu , unfortunately at the moment **1Click-HPC** only supports `AUTO` in the _Active Directory_ field.
In this case, `AUTO` means: it will build and attach automatically an AD dedicated to the cluster, as of today and external or a pre-existing AD can't be use.
Feel free to clone the git repo, make your modifications (and if you feel comfortable send a PR).

Thanks

**Comment by rvencu** [comment]
Hi, thanks for confirming. I also tried the custom FSx and it seems it tries to mount it on the HeadNode but fails with an error which suggests the security groups are not properly configured.

Is custom FSx also not fully implemented?

**Comment by nicolaven** [comment]
FSx-Lustre support is fully implemented (you can use both AUTO or an existing FSX).
When using an existing FSx-Lustre, make sure the security groups are set correctly.
https://docs.aws.amazon.com/fsx/latest/LustreGuide/limit-access-security-groups.html

**Comment by rvencu** [comment]
This is great. But it seems I am not in control of the security groups 1click-hpc uses. I have my own that are working just not sure how to specify them
