### ISSUE TITLE
pcluster update-cluster is deleting slurmdbd service

### ISSUE THREAD

**Issue by rvencu** [aws-samples/1click-hpc#29]
Updating the cluster config from the Cloud9 instance is removing the slurmdbd service.

I am not sure maybe there is a personalized update procedure via enginframe portal instead?

**Comment by rvencu** [comment]
ok, manually starting slurmdbd works, so the config is not broken. But this does not start automatically, there is no service defined and maybe it should.

I do not know if not starting slurmdbd is by design or it should be corrected

**Comment by nicolaven** [comment]
it should be fixed now, thanks for pointing this out!

https://github.com/aws-samples/1click-hpc/commit/a46411b2306fbf34555cee6b7f8c4061876b6974

**Comment by rvencu** [comment]
yes, changing the service to this seems to work:
```
[Unit]
Description=Slurm DB controller daemon
After=network.target munge.service slurmctld.service
ConditionPathExists=/opt/slurm/etc/slurmdbd.conf

[Service]
Type=oneshot
ExecStart=/opt/slurm/sbin/slurmdbd
ExecReload=/bin/kill -HUP $MAINPID
LimitNOFILE=65536
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
```
