### ISSUE TITLE
Slurm DB always get set as db.t4g.micro no matter what option is used

### ISSUE THREAD

**Issue by rvencu** [aws-samples/1click-hpc#30]
need bigger instances cause for large fleets this small instance db.t4g.micro is unable to respond in time when large jobs are launched

**Comment by nicolaven** [comment]
Absolutely, make sense.
The reason why I used this instance is because it is within the free tier but feel free to set a bigger one here: https://github.com/aws-samples/1click-hpc/blob/main/Templates/AWS-HPC-Cluster.yaml#L84

**Comment by rvencu** [comment]
Yes, what I am saying, setting it differently still result in getting db.t4g.micro

No idea why it happens

**Comment by nicolaven** [comment]
so, what you are saying is that you have a different instance type in your custom CF template **set accordingly to the region** where you plan to deploy the new cluster, then you built a new cluster using your template and you are still getting the t4g ?
(please note I fear stack updates are not supported)

**Comment by rvencu** [comment]
Yes. It seems weird but this is what happens. For good measure I put all regions with same other instance type and still getting the t4g one

With a clean, new install

Obțineți Outlook pentru iOS<https://aka.ms/o0ukef>
________________________________
De la: Nicola Venuti ***@***.***>
Trimis: Tuesday, July 12, 2022 12:56:34 PM
Către: aws-samples/1click-hpc ***@***.***>
Cc: Richard Vencu ***@***.***>; Author ***@***.***>
Subiect: Re: [aws-samples/1click-hpc] Slurm DB always get set as db.t4g.micro no matter what option is used (Issue #30)


so, what you are saying is that you have a different instance type in your custom CF template set accordingly to the region where you plan to deploy the new cluster, then you built a new cluster using your template and you are still getting the t4g ?
(please note I fear stack updates are not supported)

**Comment by nicolaven** [comment]
there must be something wrong, can you please hardcode the instance type, like:
```
DBInstanceClass: 'db.m6gd.16xlarge'
```
and try again

Thanks

**Comment by rvencu** [comment]
tested with `DBInstanceClass: 'db.m6g.8xlarge'` and I still get the t4g
