### ISSUE TITLE
Capacity/Production Readiness

### ISSUE THREAD

**Issue by c200chromebook** [aws-samples/1click-hpc#7]
All,

Stumbled on this while struggling to get slurmrestd set up on pcluster. It looks like this provides a lot of friendly wrappers for HPC type problems. Is this code production-ready? Does it support GPU instances? Is there an API provided?

**Comment by nicolaven** [comment]
Hi there,

In general the code that you find on https://github.com/aws-samples is not supposed to be used in production but instead as a sample code, snippets, you use your projects. 

About to your questions:
- This particular project is constantly updated, maintained, and is also used by a number of customer in production environments. AWS does not commit on supporting it but we typically fix problem or respond to features requests in an "affordable effort" manner.
 
- if you are looking for examples of how to use a Slurm REST API, you can have a look at this:
https://aws.amazon.com/blogs/hpc/using-the-slurm-rest-api-to-integrate-with-distributed-architectures-on-aws/

- yes it does support GPUs see here: https://github.com/aws-samples/1click-hpc/blob/main/parallelcluster/config.us-east-1.sample.yaml#L165
in particular, the GPU instances can be uses for compute jobs or for running (3D) interactive applications (using Nice DCV).

- No there is no API specifically developed for this project but most of the component/services used by this project do have an API:
a. ParallelCluster 3.X has an API https://docs.aws.amazon.com/parallelcluster/latest/ug/api-reference-v3.html 
b. Nice EnginFrame has a REST API (as well as a wsdl web services interface): https://dn3uclhgxk1jt.cloudfront.net/enginframe/packages/2020.1/documentation/EFAdminGuide2020.1.pdf
